version: '2.4'

services:
  nest:
    build: .
    ports:
      - 3000:3000
    env_file:
      - ./docker.env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: npm run start:dev

  db:
    image: postgres:13.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      #GOOD: created a named volume so our data is kept between docker-compose ups
      - postgresdb:/var/lib/postgresql/data
    env_file:
      - ./docker.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresdb:
